version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=ec2-176-34-211-0.eu-west-1.compute.amazonaws.com
      - POSTGRES_DB=d9u70h2jlv1je7
      - POSTGRES_USER=pnzugabbozwfhm
      - POSTGRES_PASSWORD=4e7d47d0f3cd434c44d344a0d69381a4ef5a46ff09a86c25084c1ced19b0cb4f
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=ec2-176-34-211-0.eu-west-1.compute.amazonaws.com
      - POSTGRES_NAME=d9u70h2jlv1je7
      - POSTGRES_USER=pnzugabbozwfhm
      - POSTGRES_PASSWORD=4e7d47d0f3cd434c44d344a0d69381a4ef5a46ff09a86c25084c1ced19b0cb4f
    depends_on:
      - db