REGISTRATION_REQUIRED_FIELDS = [
        'password',
        'first_name',
        'last_name',
        'email',
        'patronymic',
        'city',
        'gender',
        'b_date',
        'photo'
    ]

GENDERS = [('Man', 'Мужчина'), ('Woman', 'Женщина')]

STATUSES = [(1, 'Запрос отправлен'), (2, 'В друзьях')]

HOUSE = 'House'
BUSINESS = 'Business'
ROMANCE = 'Romance'
FAMILY_AND_CHILDREN = 'Family and children'
FOOD_AND_DRINKS = 'Food and drinks'
PRACTICAL_THINGS = 'Practical things'
HUMOUR_AND_SOUVENIRS = 'Humour and souvenirs'
GAMES_AND_TOYS = 'Games and toys'
COLLECTING = 'Collecting'
BEAUTY_AND_CARE = 'Beauty and care'
JEWELRY = 'Jewelry'
FASHION_AND_STYLE = 'Fashion and style'
DACHA = 'Dacha'
OTHER = 'Other'

CATEGORIES = [
    (HOUSE, 'Дом'),
    (BUSINESS, 'Бизнес'),
    (ROMANCE, 'Романтика'),
    (FAMILY_AND_CHILDREN, 'Семья и дети'),
    (FOOD_AND_DRINKS, 'Еда и напитки'),
    (PRACTICAL_THINGS, 'Практичные вещи'),
    (HUMOUR_AND_SOUVENIRS, 'Юмор и сувениры'),
    (GAMES_AND_TOYS, 'Игры и игрушки'),
    (COLLECTING, 'Коллекционирование'),
    (BEAUTY_AND_CARE, 'Красота и уход'),
    (JEWELRY, 'Украшения'),
    (FASHION_AND_STYLE, 'Мода и стиль'),
    (DACHA, 'Дача'),
    (OTHER, 'Другие разделы'),
]

SUB_CATEGORIES = [
    ('Housing', 'Все для дома'),
    ('Plays', 'Пледы'),
    ('Pillows', 'Подушки'),
    ('Towels', 'Полотенца'),
    ('Bathroom accessories', 'Аксессуары для ванной'),
    ('Kitchen accessories', 'Кухонные принадлежности'),
    ('Vases', 'Вазы'),
    ('Alarms', 'Будильники'),
    ('Photo frames', 'Фоторамки'),
    ('Wall Clock', 'Настенные часы'),
    ('Lamps', 'Лампы'),
    ('Photocartes', 'Фотокартины'),
    ('Keyroot', 'Ключницы'),
    ('Interior decor', 'Декор для интерьера'),
    ('Biocamines', 'Биокамины'),
    ('Storage and order', 'Хранение и порядок'),
    ('Gifts to the chef', 'Подарки шефу'),
    ('Business Assessies', 'Бизнес-аксессуары'),
    ('Corporate souvenirs', 'Корпоративные сувениры'),
    ('Table sets', 'Настольные наборы'),
    ('Written sets', 'Письменные наборы'),
    ('Gift pens', 'Подарочные ручки'),
    ('Diary', 'Ежедневники'),
    ('Books-Seephas', 'Книги-сейфы'),
    ('Pocket business brothers', 'Карманные визитницы'),
    ('Table businessmakers', 'Настольные визитницы'),
    ('Desk clock', 'Настольные часы'),
    ('Hourglass', 'Песочные часы'),
    ('Business statutes', 'Бизнес-статуэтки'),
    ('Antistresses', 'Антистрессы'),
    ('Globes-bars', 'Глобусы-бары'),
    ('Business portfolios', 'Деловые портфели'),
    ('Romantic things', 'Романтические вещи'),
    ('Gifts for two', 'Подарки для двоих'),
    ('Paired t -shirts', 'Парные футболки'),
    ('Hearts', 'Сердечки'),
    ('Postcards', 'Открытки'),
    ('Certificates for two', 'Сертификаты для двоих'),
    ('Breakfast tables', 'Столики для завтрака'),
    ('Gifts for the wedding', 'Подарки на свадьбу'),
    ('For the whole family', 'Для всей семьи'),
    ('Genealogies', 'Родословные книги'),
    ('"Fammily look"', '«Фэмили лук»'),
    ('Photo albums', 'Фотоальбомы'),
    ('Young parents', 'Молодым родителям'),
    ('Newborn', 'Новорожденным'),
    ('Frames for the photo of the baby', 'Рамки для фото малыша'),
    ('T -shirts for future mothers', 'Футболки для будущих мам'),
    ('Delicious gifts', 'Вкусные подарки'),
    ('Fruit baskets', 'Фруктовые корзины'),
    ('Sweets', 'Сладости'),
    ('Honey as a gift', 'Мед в подарок'),
    ('Chocolate', 'Шоколад'),
    ('Cookies and cakes', 'Печенье и пирожные'),
    ('Sephir and Marmelad', 'Зефир и мармелад'),
    ('Jam and jam', 'Варенье и джемы'),
    ('Candies', 'Конфеты'),
    ('Candy stand', 'Букеты из конфет'),
    ('Bouquets of fruit', 'Букеты из фруктов'),
    ('Chocolate cards', 'Шоколадные открытки'),
    ('Coffee', 'Кофе'),
    ('Tea', 'Чай'),
    ('All for gourmets', 'Все для гурманов'),
    ('Useful gifts', 'Полезные подарки'),
    ('Appliances', 'Бытовая техника'),
    ('Tool sets', 'Наборы инструментов'),
    ('Kitchen tools', 'Кухонные инструменты'),
    ('Lunchboxes', 'Ланчбоксы'),
    ('Caskets for the clock', 'Шкатулки для часов'),
    ('Jewelry box', 'Шкатулки для украшений'),
    ('Stands for jewelry', 'Подставки для украшений'),
    ('Columns', 'Колонки'),
    ('Headphones', 'Наушники'),
    ('Flash drives', 'Флешки'),
    ('Batteries', 'Аккумуляторы'),
    ('Laptop bags', 'Сумки для ноутбука'),
    ('Phone covers', 'Чехлы для телефонов'),
    ('Salt lamps', 'Солевые лампы'),
    ('Taberteans', 'Таблетницы'),
    ('Jokes', 'Приколы'),
    ('Men\'s T-Shirts', 'Мужские футболки'),
    ('Women\'s T-shirts', 'Женские футболки'),
    ('Aprons', 'Фартуки'),
    ('Mugs', 'Кружки'),
    ('Figurines', 'Статуэтки'),
    ('Piggy banks', 'Копилки'),
    ('Posters', 'Постеры'),
    ('Name gifts', 'Именные подарки'),
    ('Newspapers', 'Газеты'),
    ('Photo letters', 'Фотоподарки'),
    ('Figures from the photo', 'Фигурки по фото'),
    ('Portraits and cartoons', 'Портреты и шаржи'),
    ('Diplomas', 'Дипломы'),
    ('Awards', 'Награды'),
    ('Piglots for traffic jams', 'Копилки для пробок'),
    ('Stuffed Toys', 'Мягкие игрушки'),
    ('Board games', 'Настольные игры'),
    ('Chess', 'Шахматы'),
    ('Backgammon', 'Нарды'),
    ('Puzzles', 'Пазлы'),
    ('Poker', 'Покер'),
    ('"Drunk" games', '«Пьяные» игры'),
    ('Games "for adults"', 'Игры «для взрослых»'),
    ('Collecting items', 'Предметы коллекционирования'),
    ('Car models', 'Модели автомобилей'),
    ('Models of ships', 'Модели кораблей'),
    ('Models of aircraft', 'Модели самолетов'),
    ('Figures of the characters', 'Фигурки персонажей'),
    ('Porcelain dolls', 'Фарфоровые куклы'),
    ('Coins', 'Монеты'),
    ('Everything for beauty', 'Все для красоты'),
    ('Mirrors', 'Зеркала'),
    ('Manicure sets', 'Маникюрные наборы'),
    ('Cosmetic bags', 'Косметички'),
    ('Aromatic soap', 'Ароматическое мыло'),
    ('Spa treaters', 'СПА-процедуры'),
    ('Massagers', 'Массажеры'),
    ('Conductive cosmetics', 'Уходовая косметика'),
    ('Neckia and pendants', 'Колье и кулоны'),
    ('Brooches', 'Броши'),
    ('Earrings', 'Серьги'),
    ('Cufflinks', 'Запонки'),
    ('Bracelets', 'Браслеты'),
    ('Rings', 'Кольца'),
    ('Ladies Watch', 'Женские часы'),
    ('Men\'s Watch', 'Мужские часы'),
    ('Elements of style', 'Элементы стиля'),
    ('Tailoring', 'Пошив одежды'),
    ('Silk scarves', 'Шелковые платки'),
    ('Ties', 'Галстуки'),
    ('Men\'s socks', 'Мужские носки'),
    ('Umbrellas', 'Зонты'),
    ('Women\'s bags', 'Женские сумки'),
    ('Men\'s bags', 'Мужские сумки'),
    ('Backpacks', 'Рюкзаки'),
    ('Purse', 'Портмоне'),
    ('Wallets', 'Кошельки'),
    ('Money clips', 'Зажимы для денег'),
    ('Keys for keys', 'Брелки для ключей'),
    ('Covers for a passport', 'Обложки для паспорта'),
    ('Cover for autoDocations', 'Обложки для автодокументов'),
    ('Everything for a summer residence', 'Все для дачи'),
    ('B-B-Q', 'Барбекю'),
    ('Picnic sets', 'Наборы для пикника'),
    ('Colder bags', 'Сумки-холодильники'),
    ('Samovars', 'Самовары'),
    ('Weather stations', 'Метеостанции'),
    ('Decorative panels', 'Декоративные панно'),
    ('Garden figures', 'Садовые фигурки'),
    ('Cars', 'Автомобили'),
    ('Sport', 'Спорт'),
    ('Football', 'Футбол'),
    ('Fishing', 'Рыбалка'),
    ('Trips', 'Путешествия'),
    ('Cinema', 'Кино'),
    ('Creation', 'Творчество'),
    ('Healthy lifestyle', 'ЗОЖ'),
]
