# Generated by Django 4.0.3 on 2022-03-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Clothes', 'Одежда'), ('Electronics', 'Электроника'), ('Sport', 'Спорт'), ('Appliances', 'Бытовая техника'), ('For Home', 'Для дома'), ('Toys', 'Игрушки'), ('Other', 'Другое')], default='Other', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_users', models.ManyToManyField(related_name='booked_users', to=settings.AUTH_USER_MODEL)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.catalogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
