# Generated by Django 4.0.3 on 2022-05-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='category',
            field=models.ForeignKey(default=14, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory'),
        ),
    ]
