# Generated by Django 4.0.3 on 2022-03-15 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_catalogitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None),
        ),
    ]
