# Generated by Django 4.0.3 on 2022-03-15 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_alter_catalogitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='booked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='booked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
