# Generated by Django 4.0.3 on 2022-04-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_friend_status_alter_myuser_b_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friendship',
        ),
    ]
