# Generated by Django 4.0.3 on 2022-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to=''),
        ),
    ]
