# Generated by Django 4.0.3 on 2022-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_gift_category_alter_gift_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
