# Generated by Django 4.0.3 on 2022-05-05 06:40

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_gift_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='category',
            field=models.CharField(choices=[('House', 'Дом'), ('Business', 'Бизнес'), ('Romance', 'Романтика'), ('Family and children', 'Семья и дети'), ('Food and drinks', 'Еда и напитки'), ('Practical things', 'Практичные вещи'), ('Humour and souvenirs', 'Юмор и сувениры'), ('Games and toys', 'Игры и игрушки'), ('Collecting', 'Коллекционирование'), ('Beauty and care', 'Красота и уход'), ('Jewelry', 'Украшения'), ('Fashion and style', 'Мода и стиль'), ('Dacha', 'Дача'), ('Other', 'Другие разделы')], max_length=128),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
