# Generated by Django 4.0.3 on 2022-05-05 07:15

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_gift_category_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', backend.models.CustomUserManager()),
            ],
        ),
    ]
