# Generated by Django 4.0.3 on 2022-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='my_user/avatar/'),
        ),
    ]
